# Generated by Django 4.0.5 on 2022-07-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_extercounty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExterCounty',
            new_name='ExtraCounty',
        ),
    ]
