# Generated by Django 4.0.5 on 2022-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_subcounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='subcounty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
