# Generated by Django 4.0.5 on 2022-07-30 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_school_county_county_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='selected',
            field=models.ManyToManyField(blank=True, related_name='schools', to=settings.AUTH_USER_MODEL),
        ),
    ]
