# Generated by Django 4.0.5 on 2022-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_national_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='national',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, related_name='nationals', to='base.school'),
        ),
    ]
