# Generated by Django 4.0.5 on 2022-09-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_national_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='national',
            name='topic',
        ),
        migrations.AddField(
            model_name='national',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school'),
        ),
    ]
