# Generated by Django 4.0.5 on 2022-09-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_national_topic_national_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school'),
        ),
        migrations.AddField(
            model_name='extracounty',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school'),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school'),
        ),
    ]
